# Sticky Scroll demo: scroll inside the method, then click a pinned declaration.
class StickyDemo:
    def collect(self):
        values = []
        for index in range(3):
            values.append(index + 0)
            values.append(index + 1)
            values.append(index + 2)
            values.append(index + 3)
            values.append(index + 4)
            values.append(index + 5)
            values.append(index + 6)
            values.append(index + 7)
            values.append(index + 8)
            values.append(index + 9)
            values.append(index + 10)
            values.append(index + 11)
            values.append(index + 12)
            values.append(index + 13)
            values.append(index + 14)
            values.append(index + 15)
            values.append(index + 16)
            values.append(index + 17)
            values.append(index + 18)
            values.append(index + 19)
            values.append(index + 20)
            values.append(index + 21)
            values.append(index + 22)
            values.append(index + 23)
            values.append(index + 24)
            values.append(index + 25)
            values.append(index + 26)
            values.append(index + 27)
            values.append(index + 28)
            values.append(index + 29)
            values.append(index + 30)
            values.append(index + 31)
            values.append(index + 32)
            values.append(index + 33)
            values.append(index + 34)
            values.append(index + 35)
            values.append(index + 36)
            values.append(index + 37)
            values.append(index + 38)
            values.append(index + 39)
            values.append(index + 40)
            values.append(index + 41)
            values.append(index + 42)
            values.append(index + 43)
            values.append(index + 44)
            values.append(index + 45)
            values.append(index + 46)
            values.append(index + 47)
            values.append(index + 48)
            values.append(index + 49)
        return values

    def second(self):
        value_0 = 0
        value_1 = 1
        value_2 = 2
        value_3 = 3
        value_4 = 4
        value_5 = 5
        value_6 = 6
        value_7 = 7
        value_8 = 8
        value_9 = 9
        value_10 = 10
        value_11 = 11
        value_12 = 12
        value_13 = 13
        value_14 = 14
        value_15 = 15
        value_16 = 16
        value_17 = 17
        value_18 = 18
        value_19 = 19
        value_20 = 20
        value_21 = 21
        value_22 = 22
        value_23 = 23
        value_24 = 24
        value_25 = 25
        value_26 = 26
        value_27 = 27
        value_28 = 28
        value_29 = 29
        return value_29
