import {withHistoryLock,pruneHistoryUnlocked} from './history-retention.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {createHash,randomUUID} from 'node:crypto';
import {safePath} from './workspace.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');
export class LocalHistory{
 constructor(w,directory=process.env.HARNESS_HISTORY_DIR||path.join(os.homedir(),'.hot_plugging','history')){this.w=w;this.directory=directory;}
 get scope(){return path.join(this.directory,hash(JSON.stringify(this.w.info())));}
 async records(){try{return (await Promise.all((await fs.readdir(this.scope)).filter(n=>n.endsWith('.json')).map(async n=>{try{return JSON.parse(await fs.readFile(path.join(this.scope,n),'utf8'));}catch{return null;}}))).filter(Boolean).sort((a,b)=>b.time-a.time);}catch(e){if(e.code==='ENOENT')return [];throw e;}}
 async capture(p,external=false,reason='File Saved',provided){return withHistoryLock(this.directory,async()=>{const result=await this.captureUnlocked(p,external,reason,provided);await pruneHistoryUnlocked(this.directory);return result;});}
 async captureUnlocked(p,external=false,reason='File Saved',provided){let bytes;if(provided!==undefined)bytes=Buffer.from(provided,'base64');else if(external)bytes=await fs.readFile(p);else bytes=Buffer.from((await this.w.read(p)).data,'base64');if(bytes.length>64*1024*1024)throw Error('文件超过 64 MB，无法创建本地历史备份');const digest=hash(bytes),scope=this.scope;await fs.mkdir(scope,{recursive:true,mode:0o700});const records=await this.records(),latest=records.find(r=>r.path===p&&r.external===external);if(latest?.hash===digest&&latest.reason===reason)return latest;
 const blob=path.join(scope,digest+'.blob');try{await fs.writeFile(blob,bytes,{flag:'wx',mode:0o600});}catch(e){if(e.code!=='EEXIST')throw e;}const record={id:randomUUID(),path:p,external,reason,time:Date.now(),hash:digest,size:bytes.length};await fs.writeFile(path.join(scope,record.id+'.json'),JSON.stringify(record),{flag:'wx',mode:0o600});return record;}
 async before(p,external,reason){try{await this.capture(p,external,reason);}catch(e){if(e.code==='ENOENT'||(this.w.host&&/No such file/.test(e.message)))return;throw e;}}
 async captureTree(p,reason='Before Delete'){if(this.w.host){try{await this.capture(p,false,reason);return;}catch(e){if(!/directory/i.test(e.message))throw e;}for(const entry of await this.w.list(p))await this.captureTree(p+'/'+entry.name,reason);return;}
 const full=await safePath(this.w.root,p),stat=await fs.lstat(full);if(stat.isDirectory()){for(const e of await fs.readdir(full,{withFileTypes:true})){if(e.isSymbolicLink())continue;await this.captureTree(p==='.'?e.name:p+'/'+e.name,reason);}}else await this.capture(p,false,reason);}
 async entry(id){return withHistoryLock(this.directory,()=>this.entryUnlocked(id));}
 async entryUnlocked(id){if(!/^[a-f0-9-]{36}$/.test(id))throw Error('无效历史记录');const r=JSON.parse(await fs.readFile(path.join(this.scope,id+'.json'),'utf8'));if(!/^[a-f0-9]{64}$/.test(r.hash))throw Error('历史索引损坏');const bytes=await fs.readFile(path.join(this.scope,r.hash+'.blob'));if(hash(bytes)!==r.hash)throw Error('历史内容校验失败');return {...r,data:bytes.toString('base64')};}
 async restore(id,expected){const r=await this.entry(id);let current=null;try{current=r.external?hash(await fs.readFile(r.path)):(await this.w.read(r.path)).version;}catch(e){if(e.code!=='ENOENT'&&!(this.w.host&&/No such file/.test(e.message)))throw e;}if(current!==expected)throw Error('文件已变化，请刷新后重新恢复');if(current)await this.capture(r.path,r.external,'Before Restore');
 if(this.w.host&&!r.external){if(current===null){const parts=r.path.split('/');for(let i=1;i<parts.length;i++){const dir=parts.slice(0,i).join('/');try{await this.w.remote({op:'manage',action:'create',path:dir,directory:true});}catch(e){if(!/已存在/.test(e.message))throw e;}}await this.w.remote({op:'manage',action:'create',path:r.path});current=(await this.w.read(r.path)).version;}await this.w.write(r.path,r.data,current);}
 else{const full=r.external?r.path:path.resolve(this.w.root,r.path);if(!r.external){if(!full.startsWith(this.w.root+path.sep))throw Error('历史路径越界');let parent=path.dirname(full);while(true){try{await safePath(this.w.root,path.relative(this.w.root,parent)||'.');break;}catch(e){if(e.code!=='ENOENT')throw e;parent=path.dirname(parent);}}}await fs.mkdir(path.dirname(full),{recursive:true});if(current===null)await fs.writeFile(full,Buffer.from(r.data,'base64'),{flag:'wx'});else await fs.writeFile(full,Buffer.from(r.data,'base64'));}
 await this.capture(r.path,r.external,'Restored');return {path:r.path,external:r.external};}
 async route(q){if(q.action==='list'){const all=await this.records();return {entries:all.filter(r=>q.path===undefined||(r.path===q.path&&r.external===!!q.external)).map(({hash,...r})=>r)};}if(q.action==='read')return this.entry(q.id);if(q.action==='current'){const r=await this.entry(q.id);try{return r.external?{data:(await fs.readFile(r.path)).toString('base64'),version:hash(await fs.readFile(r.path))}:await this.w.read(r.path);}catch(e){if(e.code==='ENOENT'||(this.w.host&&/No such file/.test(e.message)))return {data:null,version:null};throw e;}}if(q.action==='restore')return this.restore(q.id,q.version);throw Error('未知历史操作');}
}
