import {el,button,logMessage,menuAt,form} from '../ui.js';
export default {id:'git',requires:['api','workbench','workspace'],activate(ctx){
 const api=ctx.get('api'),wb=ctx.get('workbench');const channel=crypto.randomUUID();let alive=true,repository='.',currentContainer=null;const release=()=>{currentContainer?.replaceChildren();currentContainer=null;drafts.clear();api('git',{action:'cancel',channel}).catch(()=>{});wb.$('#git-branch').textContent='';};const drafts=new Map();const configKey=()=> 'git-source:'+JSON.stringify(ctx.get('workspace').info());let config={sourceRoot:'.',depth:2};const git=q=>api('git',{...q,...config,repo:repository,channel});
 async function diff(staged=false,path){try{const {output}=await git({action:staged?'staged':'diff',path});const element=el('section','diff-view tab-content');element.append(el('h3','',path||'Changes'));const pre=el('pre');for(const line of (output||'No changes.').split('\n'))pre.append(el('div',line.startsWith('+')?'diff-add':line.startsWith('-')?'diff-del':'',line||' '));element.append(pre);wb.open({id:'diff:'+Date.now(),title:path||'Git diff',kind:'diff',element});}catch(e){logMessage(e);}}
 async function panel(container){
  currentContainer=container;
  try{config={sourceRoot:'.',depth:2,...JSON.parse(localStorage.getItem(configKey())||'{}')};}catch{config={sourceRoot:'.',depth:2};}
  const settings=el('details','settings-group git-source-settings'),summary=el('summary','','Repository Scan'),fields=el('div','settings-group-body');settings.append(summary,fields);
  const source=el('input'),depth=el('input');source.value=config.sourceRoot;source.placeholder=ctx.get('workspace').info().root;source.setAttribute('aria-label','Scan directory');depth.type='number';depth.min=0;depth.max=10;depth.value=config.depth;depth.setAttribute('aria-label','Scan depth');fields.append(el('label','','Directory (absolute or workspace-relative)'),source,el('label','','Depth (root = 0)'),depth,button('Apply & Scan','Apply & Scan',()=>{const n=Number(depth.value);if(!source.value.trim()||!Number.isInteger(n)||n<0||n>10)throw Error('Enter a directory and depth from 0 to 10');config={sourceRoot:source.value.trim(),depth:n};repository='.';localStorage.setItem(configKey(),JSON.stringify(config));return wb.showPanel('git');}));
  container.append(settings,el('p','panel-note','Loading…'));
  try{const {repositories}=await git({action:'repositories'});if(!alive||currentContainer!==container||!container.isConnected)return;if(repositories.length&&!repositories.some(r=>r.path===repository))repository=repositories[0].path;const data=await git({action:'status'});if(!alive||currentContainer!==container||!container.isConnected)return;container.replaceChildren(settings);container.classList.add('git-panel');
   if(repositories.length>1){const select=el('select','git-repository');select.setAttribute('aria-label','Repository');for(const repo of repositories){const option=el('option','',repo.root.split('/').pop());option.value=repo.path;option.title=repo.path;select.append(option);}select.value=repository;select.onchange=()=>{repository=select.value;wb.showPanel('git');};container.append(select);}
   if(!data.repository){wb.$('#git-branch').textContent='';container.append(el('p','panel-note','No Git repository in this workspace.'),button('Open Folder…','Open a repository',()=>wb.run('workspace.open')),button('Initialize Repository','Initialize Repository',async()=>{await git({action:'init'});await wb.showPanel('git');}));return;}
   const repo=repository,draftKey=data.root;const sourceConfig={...config},action=q=>api('git',{...q,...sourceConfig,repo});wb.$('#git-branch').textContent=data.branch;
   const header=el('div','git-actions');if(repositories.length<=1){const name=el('strong','git-repo-name',data.root.split('/').pop());name.title=data.root;container.append(name);}const branch=button('⑂ '+data.branch+' ▾','Switch branch',async()=>{const {branches}=await action({action:'branches',channel});if(currentContainer!==container)return;const r=branch.getBoundingClientRect();menuAt(r.left,r.bottom,[{label:'Create New Branch…',run:async()=>{const value=await form('Create New Branch',[{name:'name',label:'Branch name'}],'Create');if(!value)return;await action({action:'createBranch',branch:value.name.trim()});if(currentContainer===container)await wb.showPanel('git');}},null,...branches.map(name=>({label:name,checked:name===data.branch,run:async()=>{await action({action:'switch',branch:name});if(currentContainer===container)await wb.showPanel('git');}}))]);},'git-current-branch');branch.title=data.branch;header.append(branch,button('↻','Refresh',()=>wb.showPanel('git')));container.append(header);const sync=el('div','git-sync');for(const operation of ['pull','push']){const b=button(operation==='pull'?'↓ Pull':'↑ Push',operation,async()=>{b.disabled=true;try{await action({action:operation});if(currentContainer===container)await wb.showPanel('git');}finally{b.disabled=false;}});sync.append(b);}container.append(sync);
   const message=el('input','git-message');message.placeholder='Commit message…';message.setAttribute('aria-label','Commit message');const commit=button('✓ Commit','Commit staged changes',async()=>{commit.disabled=true;try{await action({action:'commit',message:message.value});drafts.delete(draftKey);if(currentContainer===container&&container.isConnected)await wb.showPanel('git');}finally{updateCommit();}});message.value=drafts.get(draftKey)||'';const updateCommit=()=>commit.disabled=!message.value.trim()||!data.files.some(f=>f.x!==' '&&f.x!=='?');message.oninput=()=>{drafts.set(draftKey,message.value);updateCommit();};updateCommit();commit.classList.add('git-commit');const composer=el('div','git-composer');composer.append(message,commit);container.append(composer);
   for(const [title,staged]of [['Staged Changes',true],['Changes',false]]){const files=data.files.filter(f=>staged?f.x!==' '&&f.x!=='?':f.y!==' '||f.x==='?');if(!files.length)continue;const group=el('details','git-group');group.open=true;const summary=el('summary');summary.append(el('span','git-group-title',title),el('span','git-count',String(files.length)));group.append(summary);for(const f of files){const row=el('div','git-file');const filename=f.path.split('/').pop();row.title=f.path;row.append(button(filename,'Open changes',()=>f.x==='?'?wb.run('file.open')(ctx.get('workspace').info().host?(repository==='.'?f.path:repository+'/'+f.path):data.root+'/'+f.path,{external:!ctx.get('workspace').info().host}):diff(staged,f.path)),el('span','git-status',f.x==='?'?'U':staged?f.x:f.y),button(staged?'−':'+',staged?'Unstage':'Stage',async()=>{await action({action:staged?'unstage':'stage',path:f.path});if(currentContainer===container&&container.isConnected)await wb.showPanel('git');}));group.append(row);}container.append(group);}
   if(!data.files.length)container.append(el('p','panel-note','No changes.'));
  }catch(e){if(!alive||currentContainer!==container||!container.isConnected)return;container.replaceChildren(settings,el('p','panel-note',e.message));}
 }
 ctx.on('sidebar.leaving',({id,next})=>{if(id==='git'&&next!=='git')release();});ctx.on('sidebar.visibility',({id,visible})=>{if(id==='git'&&!visible)release();});
 ctx.effect(()=>{release();alive=false;wb.$('#git-branch').textContent='';});ctx.effect(wb.panel('git','Source Control','⑂',panel));ctx.effect(wb.command('git.open','Git · Source Control',()=>wb.showPanel('git')));ctx.on('workspace.changed',()=>{wb.$('#git-branch').textContent='';});
}};
