import {el,button} from '../ui.js';
const info={terminal:['终端','开发工具'],git:['Git 版本控制','开发工具'],remote:['远程连接','开发工具'],editing:['代码编辑','开发工具'],search:['全局搜索','开发工具'],timeline:['文件历史','开发工具'],markdown:['Markdown','文件预览'],html:['HTML','文件预览'],pdf:['PDF','文件预览'],themes:['主题','界面与系统'],keybindings:['键盘快捷键','界面与系统'],explorer:['文件资源管理器','界面与系统'],documents:['文档管理','界面与系统'],'plugin-manager':['插件管理','界面与系统'],bridge:['原生桥接','界面与系统'],workbench:['工作台','界面与系统'],startup:['启动服务','界面与系统']};
export default {id:'plugin-manager',requires:['workbench'],activate(ctx){const wb=ctx.get('workbench');let statusNode;ctx.on('hot.status',message=>{if(statusNode)statusNode.textContent=message;});ctx.effect(wb.panel('plugins','Plugins','⊞',container=>{
 const root=el('div','plugins-browser'),toolbar=el('div','plugins-toolbar'),search=el('input','plugins-search');search.placeholder='搜索插件…';search.setAttribute('aria-label','搜索插件');
 const status=el('span','plugins-update-status',(()=>{try{return ctx.get('hot-updates').status();}catch{return 'Initializing updates…';}})());statusNode=status;
 toolbar.append(status,button('↻','Check for Updates',()=>ctx.get('hot-updates').check()));const list=el('div','plugins-list'),error=el('p','plugins-error');error.hidden=true;root.append(search,toolbar,error,list);container.append(root);
 const control=ctx.get('plugin-control');
 const render=()=>{list.replaceChildren();const query=search.value.toLowerCase().trim();const items=control.list().filter(i=>(i.id+' '+(info[i.id]||[]).join(' ')).toLowerCase().includes(query));
 for(const category of ['开发工具','文件预览','界面与系统','其他']){const members=items.filter(i=>(info[i.id]?.[1]||'其他')===category);if(!members.length)continue;const group=el('details','plugins-group');group.open=true;const heading=el('summary','',category);heading.append(el('span','plugins-count',String(members.length)));group.append(heading);
 for(const item of members){const row=el('div','plugin-tile'),top=el('div','plugin-tile-heading'),name=el('strong','',info[item.id]?.[0]||item.id),state=el('span','plugin-state '+(item.loaded?'is-enabled':''),item.core?'内置':item.loaded?'已启用':item.state==='uninstalled'?'未安装':'已停用');top.append(name,state);row.append(top,el('span','plugin-id',item.id));
 if(!item.core){const actions=el('div','plugin-tile-actions');const change=async next=>{error.hidden=true;try{await control.change(item.id,next);render();}catch(e){error.textContent=e.message;error.hidden=false;}};if(item.state==='uninstalled')actions.append(button('安装','Install '+item.id,()=>change('enabled')));else actions.append(button(item.loaded?'停用':'启用',(item.loaded?'Disable ':'Enable ')+item.id,()=>change(item.loaded?'disabled':'enabled')),button('卸载','Uninstall '+item.id,()=>change('uninstalled')));row.append(actions);}group.append(row);}list.append(group);}
 if(!items.length)list.append(el('p','panel-note','没有匹配的插件'));};search.oninput=render;render();
}));}};
