import {inputDragSelection} from '../input-drag-selection.js';
import {addSearchFolder} from '../search-folder.js';
import {el,button,logMessage} from '../ui.js';
export default {id:'search',requires:['api','workbench','workspace'],activate(ctx){
 const api=ctx.get('api'),wb=ctx.get('workbench'),panel=el('section','search-panel');const channel=crypto.randomUUID(),cancelSearch=()=>api('search',{channel,cancel:true}).catch(()=>{});let revision=0,timer,lastMatches=[],onlyOpen=false,listMode=false;
 const tools=el('div','search-tools'),row=el('div','search-query-row'),query=el('input'),include=el('input'),exclude=el('input'),status=el('p','search-summary'),results=el('div','search-results');
 query.placeholder='Search';query.setAttribute('aria-label','Search workspace');include.placeholder='e.g. *.ts, src/**';exclude.placeholder='e.g. *.log, build/**';
 const options={caseSensitive:false,word:false,regex:false};
 const replacement=el('input'),replaceRow=el('div','search-replace-row'),fields=el('div','search-fields');let preserveCase=false;
 for(const input of [query,include,exclude,replacement])inputDragSelection(input);
 replacement.placeholder='Replace';replacement.setAttribute('aria-label','Replace workspace');replaceRow.hidden=true;replaceRow.id='workspace-replace-row';
 const toggle=button('','Toggle Replace',()=>{replaceRow.hidden=!replaceRow.hidden;toggle.classList.toggle('codicon-chevron-down',!replaceRow.hidden);toggle.classList.toggle('codicon-chevron-right',replaceRow.hidden);toggle.setAttribute('aria-expanded',String(!replaceRow.hidden));},'search-replace-toggle codicon-chevron-right');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-controls',replaceRow.id);
 const preserve=button('AB','Preserve Case',()=>{preserveCase=!preserveCase;preserve.classList.toggle('on',preserveCase);preserve.setAttribute('aria-pressed',String(preserveCase));});
 const replaceAll=button('⇉','Replace All · 修改保留在编辑器中，可撤销；保存后写入文件',async()=>{
  if(!query.value)return;replaceAll.disabled=true;
  try{const q={search:query.value,include:include.value,exclude:exclude.value,...options,paths:onlyOpen?wb.tabs.filter(t=>t.path&&!t.external).map(t=>t.path):undefined},withCase=preserveCase,value=replacement.value,overlays={};for(const t of wb.tabs)if(t.path&&!t.external&&t.editor)overlays[t.path]=t.editor.value;
   const data=await api('search',{...q,overlays});if(data.truncated)throw Error('结果超出上限，请缩小搜索范围后替换');
   const escaped=q.search.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),raw=q.regex?q.search:escaped;
   const regex=new RegExp(q.word?'(?<![\\p{L}\\p{N}_])(?:'+raw+')(?![\\p{L}\\p{N}_])':raw,'gu'+(q.caseSensitive?'':'i'));
   let count=0;for(const path of new Set(data.matches.map(h=>h.path))){await wb.run('file.open')(path);const t=wb.active(),e=t?.editor;if(!e)continue;const next=e.value.split('\n').map(line=>line.replace(regex,(...args)=>{count++;const match=args[0];let result=value;if(q.regex){const groups=typeof args.at(-1)==='object'?args.at(-1):null;const offset=args[args.length-(groups?3:2)];const captures=args.slice(1,args.length-(groups?3:2));result=value.replace(/\$(\$|&|`|'|[1-9][0-9]?|<[^>]+>)/g,(token,key)=>key==='$'?'$':key==='&'?match:key==='`'?line.slice(0,offset):key==="'"?line.slice(offset+match.length):key.startsWith('<')?(groups?.[key.slice(1,-1)]??token):(captures[Number(key)-1]??token));}if(withCase&&match){if(match===match.toUpperCase())result=result.toUpperCase();else if(match===match.toLowerCase())result=result.toLowerCase();else if(match[0]===match[0].toUpperCase()&&match.slice(1)===match.slice(1).toLowerCase())result=result.charAt(0).toUpperCase()+result.slice(1).toLowerCase();}return result;})).join('\n');if(next!==e.value){e.value=next;t.showMode?.('source');}}
   await search();logMessage('已替换 '+count+' 处；可在各文件中撤销，保存后写入磁盘');
  }finally{replaceAll.disabled=false;}
 });replaceRow.append(replacement,preserve,replaceAll);fields.append(row,replaceRow);

 async function search(){clearTimeout(timer);const id=++revision;lastMatches=[];results.replaceChildren();if(!query.value){cancelSearch();results.replaceChildren();status.textContent='';return;}status.textContent='Searching…';try{const overlays={};for(const t of wb.tabs)if(t.dirty&&t.path&&!t.external&&t.editor)overlays[t.path]=t.editor.value;const data=await api('search',{channel,search:query.value,include:include.value,exclude:exclude.value,...options,overlays,paths:onlyOpen?wb.tabs.filter(t=>t.path&&!t.external).map(t=>t.path):undefined});if(id!==revision||data.cancelled)return;lastMatches=data.matches;results.replaceChildren();const groups=new Map();for(const hit of data.matches){if(!groups.has(hit.path))groups.set(hit.path,[]);groups.get(hit.path).push(hit);}status.textContent=`${data.matches.length} results in ${groups.size} files${data.truncated?` · 仅显示前 ${data.limit||20000} 条匹配，请缩小范围查看其余结果`:''}`;let renderedGroups=0;for(const [path,hits]of groups){const group=el('details','search-file');group.open=true;const summary=el('summary'),name=el('span','search-file-name',path.split('/').at(-1)),dir=el('span','search-file-path',path.includes('/')?path.slice(0,path.lastIndexOf('/')):''),count=el('span','search-file-count',String(hits.length));summary.title=path;summary.append(name,dir,count);group.append(summary);let shown=0;const more=button('Show more','Show more matches',()=>render());function render(){more.remove();for(const hit of hits.slice(shown,shown+100)){const b=button('',path+':'+hit.line,async()=>{await wb.run('file.open')(path);const t=wb.active();t?.showMode?.('source');t?.editor?.cmEditor?.goTo(hit.line,hit.column,hit.length);},'search-hit');b.append(el('span','',hit.line+'  '),document.createTextNode(hit.text.slice(0,hit.column-1-(hit.textOffset||0))),el('mark','',hit.text.slice(hit.column-1-(hit.textOffset||0),hit.column-1-(hit.textOffset||0)+hit.length)),document.createTextNode(hit.text.slice(hit.column-1-(hit.textOffset||0)+hit.length)));group.append(b);}shown+=100;if(shown<hits.length)group.append(more);}render();results.append(group);if(++renderedGroups%20===0){await new Promise(r=>setTimeout(r,0));if(id!==revision)return;}}}catch(e){if(id===revision){results.replaceChildren();status.textContent=e.message;}}}
 tools.append(button('＋','Open Results in Editor',async()=>{await wb.run('file.newText');const t=wb.active();if(t?.editor)t.editor.value=lastMatches.map(h=>`${h.path}:${h.line}:${h.column}  ${h.text}`).join('\n');}),button('☷','Toggle List View',()=>{listMode=!listMode;results.classList.toggle('search-list-view',listMode);}),button('↻','Refresh',search),button('×','Clear Search Results',()=>{clearTimeout(timer);revision++;cancelSearch();lastMatches=[];query.value='';results.replaceChildren();status.textContent='';query.focus();}),button('⊟','Collapse All',()=>results.querySelectorAll('details').forEach(d=>d.open=false)));
 row.append(query);for(const [key,label,title]of [['caseSensitive','Aa','Match Case'],['word','ab','Match Whole Word'],['regex','.*','Use Regular Expression']]){const b=button(label,title,()=>{options[key]=!options[key];b.classList.toggle('on',options[key]);b.setAttribute('aria-pressed',String(options[key]));search();});row.append(b);}
 wb.$('.sidebar-heading').append(tools);const searchInputs=el('div','search-inputs');searchInputs.append(toggle,fields);panel.append(searchInputs);for(const [label,input]of [['files to include',include],['files to exclude',exclude]]){const l=el('div','search-filter'),header=el('div','search-filter-header'),caption=el('label','',label);input.id=label==='files to include'?'search-include':'search-exclude';caption.htmlFor=input.id;input.setAttribute('aria-label',label);const pick=button('',label==='files to include'?'Choose folder to include':'Choose folder to exclude',async()=>{const before=ctx.get('workspace').info();if(before.host)throw Error('远程工作区请填写远程目录路径');const folder=await wb.run('file.chooseFolder');if(!folder)return;const after=ctx.get('workspace').info();if(after.root!==before.root||after.host!==before.host)return;input.value=addSearchFolder(input.value,before.root,folder);await search();},'search-folder-picker codicon codicon-folder');header.append(caption,pick);l.append(header,input);panel.append(l);}const filters=[...panel.querySelectorAll('.search-filter')];const details=button('…','Toggle Search Details',()=>{const hide=!filters[0].hidden;filters.forEach(f=>f.hidden=hide);});fields.append(details);const opened=button('◫','Search Only Open Editors',()=>{onlyOpen=!onlyOpen;opened.classList.toggle('on',onlyOpen);opened.setAttribute('aria-pressed',String(onlyOpen));search();});opened.setAttribute('aria-pressed','false');filters[0].querySelector('.search-filter-header').append(opened);panel.append(status,results);
 for(const input of [query,include,exclude]){const history=[];let historyIndex=-1;input.oninput=()=>{clearTimeout(timer);timer=setTimeout(search,300);};input.onkeydown=e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){if(!history.length)return;e.preventDefault();historyIndex=Math.max(0,Math.min(history.length-1,historyIndex+(e.key==='ArrowUp'?1:-1)));input.value=history[historyIndex];search();}else if(e.key==='Enter'){e.preventDefault();if(input.value){const i=history.indexOf(input.value);if(i>=0)history.splice(i,1);history.unshift(input.value);history.splice(30);}historyIndex=-1;search();}};}
 ctx.effect(wb.panel('search','Search','⌕',container=>container.append(panel)));
 ctx.effect(wb.command('search.workspace','搜索 · 在文件中查找',async()=>{const t=wb.current(),e=t?.editor;if(e&&e.selectionEnd>e.selectionStart)query.value=e.value.slice(e.selectionStart,e.selectionEnd);wb.$('.sidebar').classList.remove('collapsed');await wb.showPanel('search');query.focus();query.select();if(query.value)search();}));ctx.on('workspace.changed',()=>{revision++;cancelSearch();lastMatches=[];results.replaceChildren();status.textContent='';});ctx.effect(()=>{clearTimeout(timer);revision++;cancelSearch();lastMatches=[];results.replaceChildren();tools.remove();});
}};
