import {el,button,menuAt,logMessage} from '../ui.js';
export default {id:'timeline',requires:['api','workbench','workspace'],activate(ctx){
 const api=ctx.get('api'),wb=ctx.get('workbench'),box=el('section','timeline-panel'),head=el('div','timeline-heading'),list=el('div','timeline-list');let selected=null,external=false,open=false,revision=0,lastKey='',timer;
 const toggle=button('','展开或折叠文件历史',()=>{open=!open;draw();if(open)refresh();});toggle.setAttribute('aria-expanded','false');head.append(toggle);head.oncontextmenu=e=>{e.preventDefault();menuAt(e.clientX,e.clientY,[{label:'刷新历史',run:refresh},{label:'查找历史／找回已删除文件',run:recover}]);};box.append(head,list);wb.$('.sidebar').append(box);ctx.effect(()=>{box.remove();clearInterval(timer);});
 function draw(){list.hidden=!open;box.classList.toggle('expanded',open);toggle.setAttribute('aria-expanded',String(open));}
 const label=r=>new Date(r.time).toLocaleString()+' · '+({'Opened':'打开时备份','Before Save':'保存前','File Saved':'文件已保存','Before Delete':'删除前备份','Before Rename':'重命名前','Before Restore':'恢复前备份','Restored':'已恢复'}[r.reason]||r.reason);
 async function restore(r){const current=await api('history',{action:'current',id:r.id});if(current.version&&!confirm('用这个历史版本恢复 '+r.path+'？当前磁盘版本也会先备份。'))return;const existing=wb.tabs.find(t=>t.path===r.path&&!!t.external===!!r.external);if(existing&&!await wb.close(existing))return;const latest=await api('history',{action:'current',id:r.id});const restored=await api('history',{action:'restore',id:r.id,version:latest.version});await wb.run('file.open')(restored.path,{external:restored.external});await wb.refreshPanel();await refresh();logMessage('已恢复 '+r.path);}
 async function preview(r,compare=false){const entry=await api('history',{action:'read',id:r.id}),bytes=Uint8Array.from(atob(entry.data),c=>c.charCodeAt(0)),element=el('section','tab-content history-preview'),actions=el('div','history-preview-actions');actions.append(el('span','',r.path+' · '+label(r)),button('恢复此版本','恢复此版本',()=>restore(r)));element.append(actions);let dispose=()=>{};
 const ext=r.path.split('.').at(-1).toLowerCase(),mime={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',svg:'image/svg+xml',pdf:'application/pdf'}[ext];if(mime){const url=URL.createObjectURL(new Blob([bytes],{type:mime})),view=el(ext==='pdf'?'iframe':'img');view.src=url;view.className='history-media';element.append(view);dispose=()=>URL.revokeObjectURL(url);}else if(bytes.slice(0,8192).includes(0))element.append(el('p','panel-note','二进制文件 · '+entry.size+' 字节，可恢复此版本'));else{const text=new TextDecoder().decode(bytes),body=el('div',compare?'history-compare':'');const left=el('section');left.append(el('h4','','历史版本'),el('pre','',text));body.append(left);if(compare){const current=await api('history',{action:'current',id:r.id}),right=el('section');right.append(el('h4','','当前磁盘版本'),el('pre','',current.data===null?'文件已删除':new TextDecoder().decode(Uint8Array.from(atob(current.data),c=>c.charCodeAt(0)))));body.append(right);}element.append(body);}wb.open({id:'history:'+r.id+':'+compare,title:'历史 · '+r.path.split('/').at(-1),kind:'history',element,dispose});}
 function row(r,full=false){const b=button('',label(r),()=>preview(r),'timeline-entry');b.append(el('span','',full?r.path:label(r)),...(full?[el('small','',label(r))]:[]));b.oncontextmenu=e=>{e.preventDefault();menuAt(e.clientX,e.clientY,[{label:'Show Contents · 查看内容',run:()=>preview(r)},{label:'Compare with File · 与当前文件比较',run:()=>preview(r,true)},{label:'Restore Contents · 恢复内容',run:()=>restore(r)}]);};return b;}
 async function refresh(){if(!open)return;const id=++revision;if(!selected){list.replaceChildren(button('找回文件','查找历史／找回已删除文件',recover),el('p','panel-note','选择文件查看历史。'));return;}try{const data=await api('history',{action:'list',path:selected,external});if(id!==revision)return;list.replaceChildren(button('找回文件','查找历史／找回已删除文件',recover),el('div','timeline-filename',selected),...data.entries.map(r=>row(r)));if(!data.entries.length)list.append(el('p','panel-note','暂无本地历史记录'));}catch(e){list.replaceChildren(el('p','panel-note',e.message));}}
 async function recover(){const dialog=el('dialog','dialog history-picker'),input=el('input'),rows=el('div','history-picker-list');input.placeholder='搜索文件路径（包含已删除文件）';input.setAttribute('aria-label','搜索历史文件');dialog.append(el('h2','','本地历史 · 找回文件'),input,rows,button('关闭','关闭历史查找',()=>dialog.close()));document.body.append(dialog);dialog.onclose=()=>dialog.remove();dialog.showModal();const {entries}=await api('history',{action:'list'});const draw=()=>{rows.replaceChildren();for(const r of entries.filter(r=>r.path.toLowerCase().includes(input.value.toLowerCase())).slice(0,300)){const entry=el('div','history-picker-row');entry.append(button(r.path+' · '+label(r),'查看 '+r.path,()=>{dialog.close();preview(r).catch(logMessage);}),button('恢复','恢复 '+r.path,()=>{dialog.close();return restore(r);}));rows.append(entry);}if(!rows.childElementCount)rows.append(el('p','panel-note','没有匹配的备份。历史从功能启用后开始记录。'));};input.oninput=draw;draw();}
 function select(p,isExternal=false){if(!p)return;selected=p;external=isExternal;lastKey=p+':'+isExternal;refresh();}
 ctx.on('explorer.selected',entry=>{if(!entry.directory)select(entry.path);});ctx.on('tabs.changed',()=>{const t=wb.active();if(t?.path&&t.kind==='file'&&lastKey!==t.path+':'+!!t.external)select(t.path,!!t.external);});ctx.on('workspace.changed',()=>{selected=null;lastKey='';refresh();});
 ctx.effect(wb.command('history.open','Timeline · 查看本地历史',p=>{if(p)select(p);open=true;draw();return refresh();}));ctx.effect(wb.command('history.recover','本地历史 · 找回已删除文件',recover));timer=setInterval(()=>{if(open&&wb.$('.sidebar').dataset.panel==='explorer')refresh();},4000);draw();
}};
