import {el,button,logMessage,form} from './ui.js';
export async function imageEditor({bytes,mime,tab,wb,save,saveAs}){
 const root=el('section','image-editor'),header=el('div','image-header'),tools=el('div','image-tools'),stage=el('div','image-stage'),canvas=el('canvas'),info=el('span','image-info');stage.tabIndex=0;stage.setAttribute('aria-label','图片编辑区');tools.hidden=true;stage.append(canvas);root.append(header,tools,stage);let zoom=1,mode='zoom',start=null,base=null,disposed=false,saved='',history=[],future=[];
 const ctx=()=>canvas.getContext('2d',{willReadFrequently:true}),snapshot=()=>canvas.toDataURL('image/png');
 const update=()=>{canvas.style.width=canvas.width*zoom+'px';canvas.style.height=canvas.height*zoom+'px';info.textContent=`${canvas.width} × ${canvas.height} · ${Math.round(zoom*100)}%`;tab.dirty=snapshot()!==saved;wb.render();};
 const limit=(w,h)=>{if(w<1||h<1||w*h>24000000||w>16000||h>16000)throw Error('图片尺寸需在 1–16000 像素内，总计不超过 2400 万像素');};
 async function load(url){const img=new Image();img.src=url;await img.decode();limit(img.naturalWidth,img.naturalHeight);canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;ctx().drawImage(img,0,0);}
 function checkpoint(){history.push(snapshot());while(history.length>1&&(history.length>20||history.reduce((n,s)=>n+s.length,0)>64*1024*1024))history.shift();future=[];}
 function commit(){update();stage.focus();}
 async function undo(redo=false){const from=redo?future:history,to=redo?history:future;if(!from.length)return;to.push(snapshot());await load(from.pop());commit();}
 function transform(w,h,draw){limit(w,h);checkpoint();const old=document.createElement('canvas');old.width=canvas.width;old.height=canvas.height;old.getContext('2d').drawImage(canvas,0,0);canvas.width=w;canvas.height=h;draw(ctx(),old);commit();}
 const fit=()=>{zoom=Math.min(1,(stage.clientWidth-40)/canvas.width,(stage.clientHeight-40)/canvas.height);zoom=Math.max(.05,zoom);update();};
 const changeZoom=factor=>{zoom=Math.max(.05,Math.min(16,zoom*factor));update();};
 const toggle=button('编辑 ▸','展开或收起图片编辑工具',()=>{tools.hidden=!tools.hidden;if(tools.hidden){mode='zoom';stage.dataset.tool='zoom';}toggle.textContent=tools.hidden?'编辑 ▸':'编辑 ▾';toggle.setAttribute('aria-expanded',String(!tools.hidden));});toggle.setAttribute('aria-expanded','false');
 header.append(toggle,button('−','缩小图片',()=>changeZoom(1/1.25)),button('+','放大图片',()=>changeZoom(1.25)),button('适应','适应窗口',fit),button('1:1','原始比例',()=>{zoom=1;update();}),info,button('覆盖保存','覆盖保存图片',()=>save()),button('另存为','图片另存为',()=>saveAs()));
 function group(title){const box=el('div','image-tool-group');box.append(el('span','image-group-title',title));tools.append(box);return box;}
 const geometry=group('变换');geometry.append(button('↶ 90°','向左旋转',()=>transform(canvas.height,canvas.width,(c,old)=>{c.translate(0,canvas.height);c.rotate(-Math.PI/2);c.drawImage(old,0,0);})),button('↷ 90°','向右旋转',()=>transform(canvas.height,canvas.width,(c,old)=>{c.translate(canvas.width,0);c.rotate(Math.PI/2);c.drawImage(old,0,0);})),button('水平翻转','水平翻转',()=>transform(canvas.width,canvas.height,(c,old)=>{c.translate(canvas.width,0);c.scale(-1,1);c.drawImage(old,0,0);})),button('垂直翻转','垂直翻转',()=>transform(canvas.width,canvas.height,(c,old)=>{c.translate(0,canvas.height);c.scale(1,-1);c.drawImage(old,0,0);})),button('尺寸','调整图片尺寸',async()=>{const d=await form('图片尺寸',[{name:'width',label:'宽度（像素）',value:canvas.width},{name:'height',label:'高度（像素）',value:canvas.height}]);if(d){const w=Math.round(Number(d.width)),h=Math.round(Number(d.height));if(!Number.isFinite(w)||!Number.isFinite(h))throw Error('请输入有效尺寸');transform(w,h,(c,old)=>{c.imageSmoothingQuality='high';c.drawImage(old,0,0,w,h);});}}));
 const drawing=group('工具'),color=el('input'),size=el('input');color.type='color';color.value='#e06c75';color.setAttribute('aria-label','画笔颜色');size.type='number';size.min=1;size.max=100;size.value=4;size.setAttribute('aria-label','笔画宽度');
 const modes=[['zoom','查看'],['crop','裁剪'],['brush','画笔'],['erase','橡皮'],['line','直线'],['arrow','箭头'],['rect','矩形'],['ellipse','椭圆'],['text','文字'],['mosaic','马赛克'],['picker','取色']];
 for(const [id,label]of modes){const b=button(label,label,()=>{mode=id;drawing.querySelectorAll('button').forEach(x=>x.classList.toggle('on',x===b));stage.dataset.tool=id;});b.classList.toggle('on',id===mode);drawing.append(b);}drawing.append(color,size);
 const adjust=group('颜色调整'),ranges={};for(const [name,label,min,max]of [['brightness','亮度',-100,100],['contrast','对比度',-100,100],['saturation','饱和度',-100,100]]){const l=el('label','',label),input=el('input');input.type='range';input.min=min;input.max=max;input.value=0;input.setAttribute('aria-label',label);ranges[name]=input;l.append(input);adjust.append(l);}
 function pixels(fn){checkpoint();const c=ctx(),image=c.getImageData(0,0,canvas.width,canvas.height);for(let i=0;i<image.data.length;i+=4)fn(image.data,i);c.putImageData(image,0,0);commit();}
 adjust.append(button('应用调整','应用颜色调整',()=>{const bright=+ranges.brightness.value*2.55,contrast=+ranges.contrast.value*2.55,k=259*(contrast+255)/(255*(259-contrast)),sat=1+ +ranges.saturation.value/100;pixels((d,i)=>{const gray=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];for(let j=0;j<3;j++)d[i+j]=k*(gray+(d[i+j]-gray)*sat-128)+128+bright;});Object.values(ranges).forEach(x=>x.value=0);}),button('灰度','转换为灰度',()=>pixels((d,i)=>{d[i]=d[i+1]=d[i+2]=.2126*d[i]+.7152*d[i+1]+.0722*d[i+2];})),button('反色','颜色反转',()=>pixels((d,i)=>{for(let j=0;j<3;j++)d[i+j]=255-d[i+j];})));
 const output=group('历史与导出'),quality=el('input');quality.type='range';quality.min=10;quality.max=100;quality.value=92;quality.setAttribute('aria-label','JPEG WebP 导出质量');output.append(button('撤销','撤销图片编辑',()=>undo()),button('重做','重做图片编辑',()=>undo(true)),button('恢复已保存','恢复到已保存图片',async()=>{checkpoint();await load(saved);commit();}),el('span','','JPEG / WebP 质量'),quality);
 const point=e=>{const r=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)/zoom)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)/zoom))};};
 function stroke(c){c.strokeStyle=color.value;c.fillStyle=color.value;c.lineWidth=Math.max(1,Math.min(100,+size.value||4));c.lineCap='round';c.lineJoin='round';}
 canvas.onpointerdown=async e=>{if(e.button!==0)return;stage.focus();if(e.altKey||mode==='zoom'){changeZoom(e.altKey?1/1.25:1.25);return;}start=point(e);if(mode==='picker'){const p=ctx().getImageData(Math.min(canvas.width-1,Math.floor(start.x)),Math.min(canvas.height-1,Math.floor(start.y)),1,1).data;color.value='#'+[...p.slice(0,3)].map(v=>v.toString(16).padStart(2,'0')).join('');start=null;return;}if(mode==='text'){const p=start;start=null;const d=await form('添加文字',[{name:'text',label:'文字'},{name:'size',label:'字号（像素）',value:32}]);if(d){checkpoint();const c=ctx();stroke(c);c.font=`${Math.max(8,Math.min(500,+d.size||32))}px sans-serif`;c.fillText(d.text,p.x,p.y);commit();}return;}checkpoint();base=ctx().getImageData(0,0,canvas.width,canvas.height);canvas.setPointerCapture(e.pointerId);if(['brush','erase'].includes(mode)){const c=ctx();stroke(c);c.beginPath();c.moveTo(start.x,start.y);}};
 canvas.onpointermove=e=>{if(!start||!canvas.hasPointerCapture(e.pointerId))return;const p=point(e),c=ctx();stroke(c);if(['brush','erase'].includes(mode)){c.globalCompositeOperation=mode==='erase'?'destination-out':'source-over';c.lineTo(p.x,p.y);c.stroke();c.globalCompositeOperation='source-over';return;}c.putImageData(base,0,0);c.beginPath();if(['rect','crop','mosaic'].includes(mode)){c.setLineDash(mode==='rect'?[]:[6,4]);c.strokeRect(start.x,start.y,p.x-start.x,p.y-start.y);c.setLineDash([]);}else if(mode==='ellipse'){c.ellipse((start.x+p.x)/2,(start.y+p.y)/2,Math.abs(p.x-start.x)/2,Math.abs(p.y-start.y)/2,0,0,Math.PI*2);c.stroke();}else{c.moveTo(start.x,start.y);c.lineTo(p.x,p.y);if(mode==='arrow'){const a=Math.atan2(p.y-start.y,p.x-start.x),len=Math.max(12,c.lineWidth*4);c.moveTo(p.x-len*Math.cos(a-.5),p.y-len*Math.sin(a-.5));c.lineTo(p.x,p.y);c.lineTo(p.x-len*Math.cos(a+.5),p.y-len*Math.sin(a+.5));}c.stroke();}};
 canvas.onpointerup=e=>{if(!start)return;const p=point(e),x=Math.floor(Math.min(start.x,p.x)),y=Math.floor(Math.min(start.y,p.y)),w=Math.floor(Math.abs(p.x-start.x)),h=Math.floor(Math.abs(p.y-start.y)),c=ctx();if(mode==='crop'||mode==='mosaic'){c.putImageData(base,0,0);if(w&&h){if(mode==='crop'){const crop=c.getImageData(x,y,w,h);canvas.width=w;canvas.height=h;ctx().putImageData(crop,0,0);}else{const tiny=document.createElement('canvas');tiny.width=Math.max(1,Math.ceil(w/12));tiny.height=Math.max(1,Math.ceil(h/12));tiny.getContext('2d').drawImage(canvas,x,y,w,h,0,0,tiny.width,tiny.height);c.imageSmoothingEnabled=false;c.drawImage(tiny,0,0,tiny.width,tiny.height,x,y,w,h);c.imageSmoothingEnabled=true;}}}start=base=null;canvas.releasePointerCapture(e.pointerId);commit();};
 canvas.onpointercancel=()=>{if(base)ctx().putImageData(base,0,0);start=base=null;};
 const url=URL.createObjectURL(new Blob([bytes],{type:mime}));try{await load(url);}finally{URL.revokeObjectURL(url);}saved=snapshot();tab.imageEditor={snapshot:()=>({image:snapshot(),saved,history,future,zoom,mode,toolsHidden:tools.hidden,quality:quality.value}),restore:async state=>{await load(state.image);saved=state.saved;history=state.history;future=state.future;zoom=state.zoom;mode=state.mode;tools.hidden=state.toolsHidden;quality.value=state.quality;update();},undo,async encode(type){const target=type==='image/jpeg'?document.createElement('canvas'):canvas;if(target!==canvas){target.width=canvas.width;target.height=canvas.height;const c=target.getContext('2d');c.fillStyle='#ffffff';c.fillRect(0,0,target.width,target.height);c.drawImage(canvas,0,0);}const result=target.toDataURL(type,+quality.value/100);if(!result.startsWith('data:'+type+';'))throw Error('当前系统不支持此导出格式，请使用 PNG 或 JPEG');return {data:result.split(',')[1],snapshot:snapshot()};},markSaved(value){saved=value;update();}};
 tab.focus=()=>stage.focus();tab.dispose=()=>{disposed=true;history=[];future=[];};requestAnimationFrame(()=>{if(!disposed)fit();});return root;
}
