import {el,button} from './ui.js';
// Canvas coordinates stay independent of zoom; the two handles move independently.
export function imageText(surface,{zoom,changed,apply}){
 let draft=null;
 const box=el('div','image-text-box'),handle=el('div','image-text-handle','拖动文字'),input=el('textarea'),bar=el('div','image-text-controls'),barHandle=el('span','image-text-handle','拖动设置'),size=el('input'),color=el('input');
 input.setAttribute('aria-label','图片文字');input.wrap='off';input.placeholder='输入文字';size.type='number';size.min=8;size.max=500;size.setAttribute('aria-label','文字字号');color.setAttribute('aria-label','文字颜色');color.placeholder='#RRGGBB';
 box.append(handle,input);bar.append(barHandle,el('span','','字号'),size,el('span','','颜色'),color,button('应用','应用文字',apply),button('取消','取消文字',()=>clear()));for(const value of ['#e06c75','#e5c07b','#98c379','#61afef','#ffffff','#282c34']){const swatch=button('','文字颜色 '+value,()=>{if(draft){draft.color=value;render();changed();}},'image-color-swatch');swatch.style.background=value;bar.append(swatch);}surface.append(box,bar);
 function render(){box.hidden=bar.hidden=!draft;if(!draft)return;const z=zoom();box.style.left=draft.x*z+'px';box.style.top=draft.y*z+'px';input.style.fontSize=draft.size*z+'px';input.style.color=draft.color;if(input.value!==draft.text)input.value=draft.text;size.value=draft.size;color.value=draft.color;bar.style.left=draft.controlsX*z+'px';bar.style.top=draft.controlsY*z+'px';}
 function clear(){draft=null;render();changed();}
 function drag(node,target){node.onpointerdown=e=>{if(e.button!==0||!draft)return;e.preventDefault();e.stopPropagation();const x=e.clientX,y=e.clientY,z=zoom(),a=target==='text'?'x':'controlsX',b=target==='text'?'y':'controlsY',oldX=draft[a],oldY=draft[b];node.setPointerCapture(e.pointerId);node.onpointermove=event=>{if(!draft||!node.hasPointerCapture(event.pointerId))return;draft[a]=Math.max(0,oldX+(event.clientX-x)/z);draft[b]=Math.max(0,oldY+(event.clientY-y)/z);render();};node.onpointerup=event=>{node.releasePointerCapture(event.pointerId);changed();};};}
 drag(handle,'text');drag(barHandle,'controls');
 input.oninput=()=>{draft.text=input.value;changed();};size.oninput=()=>{if(size.checkValidity()){draft.size=Math.max(8,Math.min(500,+size.value||32));render();changed();}};color.oninput=()=>{if(/^#[0-9a-f]{6}$/i.test(color.value)){draft.color=color.value;input.style.color=draft.color;changed();}};
 render();return {start(p,color){draft={...p,text:'',size:32,color,controlsX:p.x,controlsY:p.y+90/zoom()};render();input.focus();},snapshot:()=>draft?{...draft}:null,restore(value){draft=value?{...value}:null;render();},render,clear,apply(context){if(!draft)return;const d=draft;if(d.text){context.save();context.fillStyle=d.color;context.font=d.size+'px sans-serif';context.textBaseline='top';d.text.split('\n').forEach((line,i)=>context.fillText(line,d.x,d.y+i*d.size*1.2));context.restore();}draft=null;render();},dispose(){box.remove();bar.remove();}};
}
