import {markdownLinks,isImageLink} from './markdown-link-tokens.js';
export function markdownInteractions({element,source,tab,api,open,onError}){
 let cachedDoc,links=[],timer,card,url,generation=0,current;
 const hide=()=>{clearTimeout(timer);generation++;current=null;card?.remove();card=null;if(url)URL.revokeObjectURL(url);url=null;};
 const enabled=()=>/\.(md|markdown)$/i.test(tab.path||'');
 const at=e=>{if(!enabled())return;const a=e.target.closest?.('.markdown a,.markdown img');if(a)return {href:a.dataset.linkHref||a.getAttribute(a.tagName==='IMG'?'src':'href'),rect:a.getBoundingClientRect(),preview:true};const view=source.cmEditor?.view;if(!view?.dom.contains(e.target))return;if(view.state.doc!==cachedDoc){cachedDoc=view.state.doc;links=markdownLinks(cachedDoc.toString());}const pos=view.posAtCoords({x:e.clientX,y:e.clientY});const link=links.find(l=>pos!==null&&pos>=l.from&&pos<=l.to);return link&&{...link,rect:view.coordsAtPos(pos)};};
 const resolve=(href,image=false)=>api('markdown/link',{path:tab.path,external:!!tab.external,href,image});
 const follow=async href=>{try{const r=await resolve(href);if(r.url)await api('browser/open',{url:r.url});else if(r.anchor!==undefined){const headings=[...element.querySelectorAll('.markdown h1,.markdown h2,.markdown h3,.markdown h4,.markdown h5,.markdown h6')];headings.find(h=>h.id===r.anchor||h.textContent.toLowerCase().replace(/[^\p{L}\p{N}\s-]/gu,'').replace(/\s/g,'-')===r.anchor)?.scrollIntoView({block:'start'});}else await open(r.path,{external:r.external,previewGroup:tab.previewGroup});}catch(e){onError(e);}};
 const hover=link=>{if(!link||!isImageLink(link.href)){hide();return;}if(current===link.href)return;hide();current=link.href;const token=generation;timer=setTimeout(async()=>{try{const r=await resolve(link.href,true);if(token!==generation||!element.isConnected||!element.getClientRects().length)return;let src=r.url;if(!src){const bytes=Uint8Array.from(atob(r.data),c=>c.charCodeAt(0));url=URL.createObjectURL(new Blob([bytes],{type:r.mime}));src=url;}card=document.createElement('div');card.className='markdown-image-hover';card.setAttribute('role','tooltip');const img=document.createElement('img');img.alt='图片预览';img.src=src;img.onerror=hide;card.append(img);document.body.append(card);const rect=link.rect;card.style.left=Math.max(8,Math.min(rect.left,innerWidth-340))+'px';card.style.top=Math.max(8,rect.top>270?rect.top-260:Math.min(rect.bottom+8,innerHeight-260))+'px';}catch{if(token===generation)hide();}},300);};
 const move=e=>hover(at(e));const click=e=>{const link=at(e);if(link&&(link.preview||e.metaKey||e.ctrlKey)){e.preventDefault();e.stopPropagation();hide();follow(link.href);}};
 const key=e=>{if(e.key==='Escape')hide();};
 const focus=e=>{const a=e.target.closest?.('.markdown a');if(a)hover({href:a.getAttribute('href'),rect:a.getBoundingClientRect()});};
 element.addEventListener('focusin',focus);document.addEventListener('pointerdown',hide);element.addEventListener('pointermove',move);element.addEventListener('pointerleave',hide);element.addEventListener('click',click,true);element.addEventListener('scroll',hide,true);document.addEventListener('keydown',key);
 const observer=new MutationObserver(()=>{if(!element.isConnected||!element.getClientRects().length)hide();});observer.observe(element,{attributes:true,attributeFilter:['class','style','hidden']});
 const dispose=()=>{hide();element.removeEventListener('focusin',focus);document.removeEventListener('pointerdown',hide);observer.disconnect();element.removeEventListener('pointermove',move);element.removeEventListener('pointerleave',hide);element.removeEventListener('click',click,true);element.removeEventListener('scroll',hide,true);document.removeEventListener('keydown',key);cachedDoc=null;links=[];};
 dispose.hide=hide;
 dispose.showHover=()=>{const view=source.cmEditor?.view;if(!enabled()||!view)return;const pos=view.state.selection.main.head;const link=markdownLinks(view.state.doc.toString()).find(l=>pos>=l.from&&pos<=l.to);if(link)hover({...link,rect:view.coordsAtPos(pos)});};return dispose;
}
