import {sourceSticky} from './source-sticky.js';
import {TokenCache} from '../shared/token-cache.js';
import {editorOverview} from './editor-overview.js';
import {assetURL} from './asset-url.js';
import {EditorState,EditorSelection,StateEffect,Compartment} from '@codemirror/state';
import {EditorView,keymap,lineNumbers,drawSelection,rectangularSelection,crosshairCursor,highlightActiveLineGutter,ViewPlugin,Decoration} from '@codemirror/view';
import * as commands from '@codemirror/commands';
import {search,openSearchPanel,selectMatches,selectSelectionMatches,selectNextOccurrence,searchPanelOpen,highlightSelectionMatches} from '@codemirror/search';
import {Registry,parseRawGrammar} from 'vscode-textmate';
import {loadWASM,OnigScanner,OnigString} from 'vscode-oniguruma';
import {createFindPanel} from './find-panel.js';
let resources;
async function load(){return resources ||= (async()=>{const [wasm,grammars,dark,light]=await Promise.all([fetch(assetURL('/syntax/onig.wasm')).then(r=>r.arrayBuffer()),fetch(assetURL('/syntax/grammars.json')).then(r=>r.json()),fetch(assetURL('/syntax/one-dark-pro.json')).then(r=>r.json()),fetch(assetURL('/syntax/light.json')).then(r=>r.json())]);await loadWASM(wasm);return {grammars,dark,light};})();}
const scopes={sshconfig:'source.ssh-config',sql:'source.sql',ini:'source.ini',conf:'source.ini',toml:'source.toml',xml:'text.xml',java:'source.java',c:'source.c',h:'source.c',cpp:'source.cpp',cs:'source.cs',go:'source.go',rs:'source.rust',rb:'source.ruby',php:'source.php',dockerfile:'source.dockerfile',md:'text.html.markdown',markdown:'text.html.markdown',html:'text.html.basic',css:'source.css',js:'source.js',ts:'source.ts',py:'source.python',sh:'source.shell',jsx:'source.js.jsx',tsx:'source.tsx',mjs:'source.js',cjs:'source.js',mts:'source.ts',cts:'source.ts',pyw:'source.python',bash:'source.shell',zsh:'source.shell',jsonc:'source.json.comments',jsonl:'source.json.lines',ndjson:'source.json.lines',json:'source.json',yaml:'source.yaml',yml:'source.yaml'};
// Share immutable theme registries across all source editors and fenced previews.
const syntaxRegistries=new Map();let syntaxUsers=0,registryCleanup;
function retainSyntax(){syntaxUsers++;clearTimeout(registryCleanup);}
function releaseSyntax(){syntaxUsers--;if(!syntaxUsers)registryCleanup=setTimeout(()=>{if(syntaxUsers)return;for(const pending of syntaxRegistries.values())pending.then(r=>r.dispose()).catch(()=>{});syntaxRegistries.clear();},60000);}

async function sharedRegistry(){const light=document.documentElement.dataset.theme==='light',key=light?'light':'dark';if(!syntaxRegistries.has(key))syntaxRegistries.set(key,(async()=>{const r=await load(),raw=light?r.light:r.dark;return new Registry({theme:{settings:[{settings:{foreground:raw.colors?.['editor.foreground']||(light?'#383a42':'#abb2bf'),background:raw.colors?.['editor.background']||(light?'#ffffff':'#282c34')}},...raw.tokenColors]},onigLib:Promise.resolve({createOnigScanner:p=>new OnigScanner(p),createOnigString:s=>new OnigString(s)}),loadGrammar:async scope=>{const file=r.grammars[scope];return file?parseRawGrammar(await fetch(assetURL('/syntax/'+file)).then(r=>r.text()),file):null;}});})().catch(error=>{syntaxRegistries.delete(key);throw error;}));return syntaxRegistries.get(key);}
const syntaxChanged=StateEffect.define();
export function sourceEditor(textarea,ext){
 retainSyntax();
 const shell=document.createElement('div');shell.className='source-editor-shell cm-shell';const tokenCache=new TokenCache();let lastTokenUse=Date.now();const cacheCleanup=setInterval(()=>{if(Date.now()-lastTokenUse>60000)tokenCache.clear();},60000);let registry,grammar,palette=[],disposed=false;
 const build=view=>{lastTokenUse=Date.now();if(!grammar)return Decoration.none;const marks=[];let stack=null;const last=view.state.doc.lineAt(view.viewport.to).number;for(let n=1;n<=last;n++){const line=view.state.doc.line(n),result=tokenCache.tokenize(grammar,n,line.text,stack);stack=result.ruleStack;if(line.to<view.viewport.from)continue;for(let j=0;j<result.tokens.length;j+=2){const from=line.from+result.tokens[j],to=j+2<result.tokens.length?line.from+result.tokens[j+2]:line.to;if(to>from){const color=palette[(result.tokens[j+1]>>>15)&511];if(color)marks.push(Decoration.mark({attributes:{style:'color:'+color}}).range(from,to));}}}return Decoration.set(marks);};
 const syntax=ViewPlugin.fromClass(class{constructor(view){this.decorations=build(view);}update(update){if(update.docChanged||update.viewportChanged||update.transactions.some(t=>t.effects.some(e=>e.is(syntaxChanged))))this.decorations=build(update.view);}},{decorations:p=>p.decorations});
 const wrapping=new Compartment();const wrapEnabled=()=>localStorage.getItem('editor-word-wrap')==='on';
 const extensions=[sourceSticky(ext),editorOverview,wrapping.of(wrapEnabled()?EditorView.lineWrapping:[]),EditorState.allowMultipleSelections.of(true),EditorState.tabSize.of(2),commands.history(),lineNumbers(),highlightActiveLineGutter(),drawSelection(),rectangularSelection({eventFilter:e=>e.button===0&&e.shiftKey&&e.altKey}),crosshairCursor({key:'Alt'}),highlightSelectionMatches(),search({top:true,literal:true,createPanel:createFindPanel}),keymap.of([...commands.defaultKeymap,...commands.historyKeymap,{key:'Tab',run:commands.indentMore},{key:'Shift-Tab',run:commands.indentLess}]),syntax,EditorView.contentAttributes.of({'aria-label':textarea.getAttribute('aria-label')||'文件内容',spellcheck:'false'}),EditorView.updateListener.of(update=>{if(update.docChanged)textarea.dispatchEvent(new Event('input',{bubbles:true}));})];
 const view=new EditorView({state:EditorState.create({doc:textarea.value,selection:{anchor:textarea.selectionStart,head:textarea.selectionEnd},extensions}),parent:shell});
 view.harnessHighlightLine=(number)=>{const line=view.state.doc.line(number);if(!grammar)return [{text:line.text}];let stack=null,result;for(let n=1;n<=number;n++){const current=view.state.doc.line(n);result=tokenCache.tokenize(grammar,n,current.text,stack);stack=result.ruleStack;}const spans=[];for(let j=0;j<result.tokens.length;j+=2){const start=result.tokens[j],end=j+2<result.tokens.length?result.tokens[j+2]:line.length;spans.push({text:line.text.slice(start,end),color:palette[(result.tokens[j+1]>>>15)&511]});}return spans;};
 textarea.hidden=true;textarea.setAttribute('aria-hidden','true');shell.append(textarea);view.contentDOM.harnessSource=textarea;
 const clamp=n=>Math.max(0,Math.min(view.state.doc.length,n));
 const own=['value','selectionStart','selectionEnd','setSelectionRange','setRangeText','focus','select'];
 Object.defineProperties(textarea,{value:{configurable:true,get:()=>view.state.doc.toString(),set:value=>{if(value!==view.state.doc.toString())view.dispatch({changes:{from:0,to:view.state.doc.length,insert:value}});}},selectionStart:{configurable:true,get:()=>view.state.selection.main.from},selectionEnd:{configurable:true,get:()=>view.state.selection.main.to}});
 const updateWrap=()=>{view.dispatch({effects:wrapping.reconfigure(wrapEnabled()?EditorView.lineWrapping:[])});view.requestMeasure();};window.addEventListener('editor-word-wrap-changed',updateWrap);
 textarea.setSelectionRange=(from,to)=>view.dispatch({selection:{anchor:clamp(from),head:clamp(to)},scrollIntoView:true});
 textarea.setRangeText=(text,from,to)=>view.dispatch({changes:{from,to,insert:text},selection:{anchor:from+text.length},userEvent:'input'});
 textarea.focus=()=>view.focus();textarea.select=()=>commands.selectAll(view);
 const replaceSelections=text=>{const rows=text.split(/\r?\n/),ranges=view.state.selection.ranges;view.dispatch(view.state.changeByRange((range,index)=>{const indexOf=ranges.indexOf(range),insert=ranges.length>1&&rows.length===ranges.length?rows[indexOf]:text;return {changes:{from:range.from,to:range.to,insert},range:EditorSelection.cursor(range.from+insert.length)};}));view.focus();};
 textarea.cmEditor={view,snapshot:()=>view.state.toJSON({history:commands.historyField}),restore:snapshot=>view.setState(EditorState.fromJSON(snapshot,{extensions},{history:commands.historyField})),replaceSelections,selectedText:()=>view.state.selection.ranges.map(r=>view.state.sliceDoc(r.from,r.to)).join('\n'),run:name=>commands[name]?.(view),openSearch(replace=false){view.harnessReplace=replace;openSearchPanel(view);view.harnessFindPanel?.showReplace(replace);},selectMatches(){if(searchPanelOpen(view.state))selectMatches(view);else{if(view.state.selection.main.empty)selectNextOccurrence(view);selectSelectionMatches(view);}view.focus();},goTo(line,column=1,length=0){const l=view.state.doc.line(Math.min(view.state.doc.lines,Math.max(1,line))),from=Math.min(l.to,l.from+column-1);view.dispatch({selection:{anchor:from,head:Math.min(view.state.doc.length,from+length)},scrollIntoView:true});view.focus();}};
 async function applyTheme(){const next=await sharedRegistry();if(disposed)return;registry=next;tokenCache.clear();grammar=scopes[ext]?await registry.loadGrammar(scopes[ext]):null;if(disposed)return;palette=registry.getColorMap();view.dispatch({effects:syntaxChanged.of(null)});}

 const observer=new MutationObserver(()=>applyTheme().catch(()=>{}));observer.observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});applyTheme().catch(()=>{});
 return {element:shell,refresh:()=>view.requestMeasure(),dispose(){if(disposed)return;disposed=true;clearInterval(cacheCleanup);tokenCache.clear();releaseSyntax();window.removeEventListener('editor-word-wrap-changed',updateWrap);const text=view.state.doc.toString(),selection=view.state.selection.main;observer.disconnect();view.destroy();delete textarea.cmEditor;for(const key of own)delete textarea[key];textarea.value=text;textarea.setSelectionRange(selection.from,selection.to);textarea.hidden=false;textarea.removeAttribute('aria-hidden');}};
}

export async function highlightCodeBlocks(article){
 retainSyntax();
 try{const registry=await sharedRegistry();for(const code of article.querySelectorAll('pre>code')){const lang=[...code.classList].find(c=>c.startsWith('language-'))?.slice(9).toLowerCase(),alias={shell:'sh',shellscript:'sh',bash:'sh',javascript:'js',typescript:'ts',python:'py',markdown:'md'};const scope=scopes[alias[lang]||lang];if(!scope)continue;const grammar=await registry.loadGrammar(scope);if(!grammar)continue;const palette=registry.getColorMap(),fragment=document.createDocumentFragment();let stack=null;const lines=code.textContent.split('\n');for(let n=0;n<lines.length;n++){const line=lines[n],result=grammar.tokenizeLine2(line,stack);stack=result.ruleStack;for(let j=0;j<result.tokens.length;j+=2){const span=document.createElement('span'),end=j+2<result.tokens.length?result.tokens[j+2]:line.length;span.textContent=line.slice(result.tokens[j],end);span.style.color=palette[(result.tokens[j+1]>>>15)&511]||'';fragment.append(span);}if(n<lines.length-1)fragment.append(document.createTextNode('\n'));}code.replaceChildren(fragment);}}
 finally{releaseSyntax();}
}
